Add API documentation for ARAnchorManager
google-ar/three.ar.js pull request #103
Opened 2018-02-26 21:52 UTC by jsantell

2018-02-27 09:38 UTC, vincentfretin commented on API.md
> +object will be updated accordingly, and a `anchorsupdated` event will be fired on the ARAnchorManager. Returns th ARAnchorManager.
th => the

2018-02-27 16:51 UTC, jsantell commented on API.md
> +object will be updated accordingly, and a `anchorsupdated` event will be fired on the ARAnchorManager. Returns th ARAnchorManager.
thanks! updated

2018-03-02 19:13 UTC, judax requested changes
Just a minor change as the event name is not "planesupdated" but "anchorsupdated".

2018-03-02 19:13 UTC, judax commented on API.md
> +Currently there's only the `planesupdated` event has an `anchors` property containing an array
The event is "anchorsupdated".

2018-03-02 19:15 UTC, jsantell commented on API.md
> +Currently there's only the `planesupdated` event has an `anchors` property containing an array
Ah good catch

2018-03-02 19:17 UTC, merged